Controllers/RemoveDriverController.cs

using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SuperPuperTaxi.Models;



namespace SuperPuperTaxi.Controllers
{
    public class RemoveDriverController : Controller
    {
        IDriverRepository db;

        public RemoveDriverController(IDriverRepository db) {
            this.db = db;
        }

        public IActionResult ShowDrivers()
        {
            ViewBag.Drivers = db.GetDriverList();
            return View();
        }

        [HttpGet]
        public IActionResult RemoveNow(int Id) {
            db.Delete(Id);
            db.Save();
            return RedirectToAction("ShowDrivers");
        }
    }
}

Views/Admin/Admin.cshtml

<form method="POST">
    <table style="text-align: left; width: 700px; height: 565px;" border="1" cellpadding="2" cellspacing="2">
        <tbody>
            <tr>
                <th style="text-align: center; background-color: rgb(109, 241, 249); height: 44px; width: 100px;" colspan="2" rowspan="1">Manager Page</th>
            </tr>
            <tr>
                <td style="width: 350px; height: 200px; text-align: center;">
                    <button name="AddDriver"
                            type="submit"
                            style="width: 100px; height: 50px; background-color: rgb(245, 204, 235); font-size: 16px;"
                            asp-controller="AddDriver" asp-action="AddDriver">
                        Add Driver
                    </button>
                </td>
                <td style="width: 350px; height: 200px; text-align: center;">

                    <button 
                        type="submit"
                        asp-controller="RemoveDriver" asp-action="ShowDrivers"
                        style="width: 100px; height: 50px; background-color: rgb(211, 238, 228); font-size: 16px;" name="RemoveDriver">
                        Remove Driver
                    </button>
                </td> 
            </tr>
        </tbody>
    </table>
</form>

